version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: |
          poetry self update
          pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
  integration-test:
    # We're using a machine executor because the docker-compose integration tests include mounting
    # a volume for the dummy trustomer config, which isn't supported with the remote docker executor.
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - run:
          name: Build docker image
          command: docker build . -t polaris-trustomer-api
      - run:
          name: Tag docker image
          command: |
            docker tag polaris-trustomer-api ghcr.io/polaris-foundation/polaris-trustomer-api:latest
            docker tag polaris-trustomer-api ghcr.io/polaris-foundation/polaris-trustomer-api:cb-${CIRCLE_BUILD_NUM}
            docker tag polaris-trustomer-api ghcr.io/polaris-foundation/polaris-trustomer-api:$(git log --pretty=format:'%h' -n 1)
      - run:
          name: Authenticate to GHCR
          command: echo $GHCR_TOKEN | docker login ghcr.io -u jonadaly --password-stdin
      - run:
          name: Push docker image
          command: |
            docker push ghcr.io/polaris-foundation/polaris-trustomer-api:latest
            docker push ghcr.io/polaris-foundation/polaris-trustomer-api:cb-${CIRCLE_BUILD_NUM}
            docker push ghcr.io/polaris-foundation/polaris-trustomer-api:$(git log --pretty=format:'%h' -n 1)
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - integration-test:
          context: polaris-foundation
      - deploy-dev:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main
